"""initial schema

Revision ID: b5bb1075a581
Revises:
Create Date: 2026-07-19 15:21:32.055841
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b5bb1075a581"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_name", sa.String(length=64), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("cost_model_version", sa.JSON(), nullable=False),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("data_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("exchange", sa.String(length=8), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("instrument_key", sa.String(length=64), nullable=False),
        sa.Column("tick_size", sa.String(length=40), nullable=False),
        sa.Column("lot_size", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instrument_key"),
        sa.UniqueConstraint("symbol", "exchange", name="uq_instrument_symbol_exchange"),
    )
    op.create_table(
        "news_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    with op.batch_alter_table("news_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_news_items_published_at"), ["published_at"], unique=False
        )

    op.create_table(
        "risk_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "LIMIT_BREACH",
                "KILL_SWITCH",
                "REJECTION",
                name="riskeventkind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_risk_events_at"), ["at"], unique=False)

    op.create_table(
        "strategy_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_name", sa.String(length=64), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("PAPER", "LIVE", "BACKTEST", name="mode", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_analyses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_analyses_instrument_id"), ["instrument_id"], unique=False
        )

    op.create_table(
        "backtest_trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backtest_run_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backtest_run_id"],
            ["backtest_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("backtest_trades", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_backtest_trades_backtest_run_id"), ["backtest_run_id"], unique=False
        )

    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("avg_price", sa.String(length=40), nullable=False),
        sa.Column("realized_pnl", sa.String(length=40), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("PAPER", "LIVE", "BACKTEST", name="mode", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instrument_id", "mode", name="uq_position_instrument_mode"),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("strategy_run_id", sa.Integer(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("LONG", "SHORT", "EXIT", name="signaldirection", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("ref_price", sa.String(length=40), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                name="signalstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_run_id"],
            ["strategy_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_signals_instrument_id"), ["instrument_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_signals_strategy_run_id"), ["strategy_run_id"], unique=False
        )

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_order_id", sa.String(length=40), nullable=False),
        sa.Column("broker_order_id", sa.String(length=64), nullable=True),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="side", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "order_type",
            sa.Enum("MARKET", "LIMIT", "SL", name="ordertype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("filled_qty", sa.Integer(), nullable=False),
        sa.Column("limit_price", sa.String(length=40), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING_RISK",
                "REJECTED_RISK",
                "SUBMITTING",
                "SUBMITTED",
                "FAILED",
                "REJECTED_BROKER",
                "OPEN",
                "PARTIALLY_FILLED",
                "FILLED",
                "CANCELLED",
                "EXPIRED",
                name="orderstate",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum("PAPER", "LIVE", "BACKTEST", name="mode", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "filled_qty >= 0 AND filled_qty <= qty", name="ck_order_filled_qty_bounds"
        ),
        sa.CheckConstraint("qty > 0", name="ck_order_qty_positive"),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_order_id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_orders_instrument_id"), ["instrument_id"], unique=False
        )
        batch_op.create_index("ix_orders_state", ["state"], unique=False)

    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column("ai_analysis_id", sa.Integer(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "BUY",
                "SELL",
                "HOLD",
                "AVOID",
                name="recommendationaction",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_analysis_id"],
            ["ai_analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendations_instrument_id"), ["instrument_id"], unique=False
        )

    op.create_table(
        "order_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column(
            "from_state",
            sa.Enum(
                "PENDING_RISK",
                "REJECTED_RISK",
                "SUBMITTING",
                "SUBMITTED",
                "FAILED",
                "REJECTED_BROKER",
                "OPEN",
                "PARTIALLY_FILLED",
                "FILLED",
                "CANCELLED",
                "EXPIRED",
                name="orderstate",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_state",
            sa.Enum(
                "PENDING_RISK",
                "REJECTED_RISK",
                "SUBMITTING",
                "SUBMITTED",
                "FAILED",
                "REJECTED_BROKER",
                "OPEN",
                "PARTIALLY_FILLED",
                "FILLED",
                "CANCELLED",
                "EXPIRED",
                name="orderstate",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_events_order_id"), ["order_id"], unique=False)

    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.String(length=40), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("brokerage", sa.String(length=40), nullable=False),
        sa.Column("stt", sa.String(length=40), nullable=False),
        sa.Column("stamp_duty", sa.String(length=40), nullable=False),
        sa.Column("gst", sa.String(length=40), nullable=False),
        sa.Column("exchange_charges", sa.String(length=40), nullable=False),
        sa.Column("sebi_charges", sa.String(length=40), nullable=False),
        sa.Column("net_amount", sa.String(length=40), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trades_order_id"), ["order_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trades_order_id"))

    op.drop_table("trades")
    with op.batch_alter_table("order_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_events_order_id"))

    op.drop_table("order_events")
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendations_instrument_id"))

    op.drop_table("recommendations")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("ix_orders_state")
        batch_op.drop_index(batch_op.f("ix_orders_instrument_id"))

    op.drop_table("orders")
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signals_strategy_run_id"))
        batch_op.drop_index(batch_op.f("ix_signals_instrument_id"))

    op.drop_table("signals")
    op.drop_table("positions")
    with op.batch_alter_table("backtest_trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backtest_trades_backtest_run_id"))

    op.drop_table("backtest_trades")
    with op.batch_alter_table("ai_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_analyses_instrument_id"))

    op.drop_table("ai_analyses")
    op.drop_table("strategy_runs")
    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_events_at"))

    op.drop_table("risk_events")
    with op.batch_alter_table("news_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_items_published_at"))

    op.drop_table("news_items")
    op.drop_table("instruments")
    op.drop_table("backtest_runs")
    # ### end Alembic commands ###
